### PR TITLE
Add a random string to skip packagist json cache

### PR DESCRIPTION
**Pull request by luckyraul**

### CODE REVIEW

**Comment by aik099** [comment]
Why using cached `packagist.json` is bad?

**Comment by luckyraul** [comment]
In my current case - 5 hours left, still no updates. If I add some param I get the updated JSON

**Comment by aik099** [comment]
Does new version show on Packagist website? If it does, but not available via API then it's something wrong with Packagist API.

**Comment by luckyraul** [comment]
Yes, It does, instantly after the tag

**Comment by aik099** [comment]
You can report a bug to the https://github.com/composer/packagist then. Keep this issue open just in case.

**Comment by webflo** [comment]
I think this is the same bug as in https://github.com/humbug/phar-updater/pull/10 / https://github.com/humbug/phar-updater/pull/51 

This fix is in ``master`` but not ``1.0``.

**Comment by luckyraul** [comment]
still have the problem

@aik099  can you merge to 1.0?

**Comment by theofidry** [comment]
I'm fine to merge and release it in 1.x if a PR is provided

**Pull request closed without merging**
